### ISSUE TITLE
Dingo api routes are not displayed

### ISSUE THREAD

**Issue by nyedidikeke** [asvae/laravel-api-tester#11]
[Dingo api](https://github.com/dingo/api) routes are currently not being captured; only default application routes `Route::` and the package's *test* ones are.

**Comment by asvae** [comment]
@nyedidikeke I'm not familliar with dingo api and currently requests are first-hand priority.

PR will be gladly accepted though :3. And I will take a look at some point, just not now.

**Comment by nyedidikeke** [comment]
@asvae: will check it up as soon as I can and send a PR.

**Comment by greabock** [comment]
@nyedidikeke Hi! You jus should impelement (RouteRepositoryInterface)[https://github.com/asvae/laravel-api-tester/blob/development/src/Contracts/RouteRepositoryInterface.php]

and override [this config line](https://github.com/asvae/laravel-api-tester/blob/development/config/api-tester.php#L44)

**Comment by greabock** [comment]
@nyedidikeke I will try to implement support for Dingo. Day or two.

**Comment by greabock** [comment]
https://github.com/asvae/laravel-api-tester/commit/4f0e6f6f2eec57391e1ed605e2dcb680db741a93
