### ISSUE TITLE
Check List For 2.0.0-beta

### ISSUE THREAD

**Issue by greabock** [asvae/laravel-api-tester#13]
**sould be**
- [x] Tidy interface
- [x] FireBase streaming
- [x] Better compatibility with Dingo
- [x] Documentation

**may be**
- [ ] ~~Lumen support~~
- [ ] ~~DataBase Storage Driver~~

**Comment by asvae** [comment]
- [ ] Optional video chat with voice recognition.

**Comment by greabock** [comment]
Nice joke )

**Comment by welcoMattic** [comment]
- [] Laravel 5.1 support ( ❤️ thanks @greabock )

**Comment by asvae** [comment]
Implemented in 2.0.0.
