### ISSUE TITLE
Not possible to publish config file

### ISSUE THREAD

**Issue by welcoMattic** [asvae/laravel-api-tester#15]
Hi, I just install your package, and I can't publish the config file.

```
Can't locate path: </Users/welcomattic/workspace/CoStreamMQ/vendor/asvae/laravel-api-tester/src/config/api-tester.php>
```

**Comment by asvae** [comment]
@welcoMattic Thanks for that.

BTW we're currently working on dev version which has like 3 times more features and also configs etc fixed and revised. We intend to publish 2.0.0-beta this week.

**Comment by welcoMattic** [comment]
Ok, I'm currently testing the dev branch. I get some errors just after installation. May I report them?

**Comment by asvae** [comment]
@welcoMattic sure. Though some of them we probably do know. If you have any ideas about interface and such be sure to share as well :).
