### ISSUE TITLE
"Class web does not exist" after clean installation

### ISSUE THREAD

**Issue by welcoMattic** [asvae/laravel-api-tester#18]
@asvae  

I caught this error just after a clean installation of the package :

```
ReflectionException (-1)
Class web does not exist
```

Is it known? 

BTW, I use dingo/api

**Comment by greabock** [comment]
Hi! Can you provide additional information? Package version, PHP version, Laravel version. Then i can try to reproduce this the error.

**Comment by welcoMattic** [comment]
Here more info : 

```
api-tester dev-development
PHP 7.0.9
Laravel 5.1.41
```

**Comment by greabock** [comment]
Thank you! Middleware groups was added in laravel 5.2. I'll to fix it now.

**Comment by welcoMattic** [comment]
Great, thank you to backport compatiblity to 5.1!

**Comment by greabock** [comment]
https://github.com/asvae/laravel-api-tester/commit/a1a40a44bb1b7593216567acb8ce25698626a70b

**Comment by welcoMattic** [comment]
It works great!

**Comment by welcoMattic** [comment]
Excepted that I can't see my dingo/api routes :/

**Comment by greabock** [comment]
you should uncomment this line
https://github.com/asvae/laravel-api-tester/blob/development/config/api-tester.php#L100

**Comment by welcoMattic** [comment]
I tried, but nothing happens.

**Comment by greabock** [comment]
I realy have no idea =(
Just tried, clean install.

PHP 5.6/7.0

composer.json
```
    "laravel/framework": "5.1.*",
    "asvae/laravel-api-tester": "dev-development",
    "dingo/api": "1.0.x@dev"
```
config/app.php
```
  Dingo\Api\Provider\LaravelServiceProvider::class,
  Asvae\ApiTester\ServiceProvider::class,
```

config/api-tester.php
```
    'route_repositories' => [
        Asvae\ApiTester\Repositories\RouteLaravelRepository::class,
        Asvae\ApiTester\Repositories\RouteDingoRepository::class,
    ],
```
config/api.php
```
    'subtype' => env('API_SUBTYPE', 'test'),
    'prefix' => env('API_PREFIX', 'api'),
```

app/Http/routes.php
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->get('users/{id}',function(){
        return 'TEst';
    });
});
```


and it works fine for me...
![proof](http://dl2.joxi.net/drive/2016/08/16/0005/0117/381045/45/b312f70dfb.jpg)

route detected,
headers auto-filled
result is returned

have you any idea?

**Comment by greabock** [comment]
did you apply latest update?
https://github.com/asvae/laravel-api-tester/commit/c98183f0304f6db36cb37a624576984635431ca9

**Comment by welcoMattic** [comment]
I just run a `composer update`

**Comment by greabock** [comment]
i don't know how to reproduce this bug =(
can you provide your dingo config?
