### ISSUE TITLE
Error on Laravel 5.1

### ISSUE THREAD

**Issue by welcoMattic** [asvae/laravel-api-tester#20]
I just pull the last 2.0.0-alpha from a composer update, and I caught this error on Laravel 5.1.41 :

```
[BadMethodCallException]
  Method resourceParameters does not exist.
```

This is due to a non-existant method on `Route` facade on 5.1 :

In asvae/laravel-api-tester/src/Http/routes.php line 3 :

```php
Route::resourceParameters(['requests' => 'request']);
```

Method `resourceParameters` doesn't exist

**Comment by welcoMattic** [comment]
EDIT: 2.0.0-alpha is not ready for 5.1.

But dev-development is ready.

**Comment by asvae** [comment]
Erm. Yeah. That's how composer tracks version. For values like `2.0.0-alpha` it checks [github releses](https://github.com/asvae/laravel-api-tester/releases). For `dev-development` it just grabs last commit from `development` branch.

Major release will fix this issue for sure.

**Comment by welcoMattic** [comment]
BTW, even in dev-development branch, my dingo/api routes are not recognized by api-tester in Laravel 5.1

**Comment by asvae** [comment]
@welcoMattic if you still experience troubles with dingo api consider creating another issue with some additional info, so that we can reproduce.

Currently, it works fine on our side.

**Comment by welcoMattic** [comment]
Hi guys!

Finally I found the source of my problem. I simply was a corrupted config cache file that the `artisan config:clear` command can not delete. Everything works like a charm now. Thanks for help ;)
