### ISSUE TITLE
Too long response

### ISSUE THREAD

**Issue by melihovv** [asvae/laravel-api-tester#24]
Hello! Thanks for such nice package, I love it!
It would be nice to add `overflox-x: auto;` to tab content (see screenshot).
![image](https://cloud.githubusercontent.com/assets/8608721/18186004/ecaabe08-70a8-11e6-8078-871d274ff17e.png)

**Comment by asvae** [comment]
Glad you like it. : 3

Added overflow as requested (v2.0.3). Thanks for mentioning.
