### ISSUE TITLE
Do not use aliases in the package

### ISSUE THREAD

**Issue by atehnix** [asvae/laravel-api-tester#27]
Do not use aliases in the package.
This forces the user to include aliases in the app configuration, even if he does not use them in own application.

See: [src/Http/routes.php](https://github.com/asvae/laravel-api-tester/blob/master/src/Http/routes.php)

**Comment by atehnix** [comment]
Moreover, you can get unpredictable behavior if the alias will refer to the other facade (not the default).

**Comment by asvae** [comment]
Thanks. That definitely should be fixed. I imagine someone could even not use aliases.

**Comment by asvae** [comment]
Fixed 0132f11e0b09afe8c41b21e75565727762600dad
