### ISSUE TITLE
Just pulled it in and got an issue registering its routes

### ISSUE THREAD

**Issue by gocanto** [asvae/laravel-api-tester#30]
[LogicException]
  Unable to prepare route [api-tester/* routes should not be cached] for serialization. Uses Closure.

**Comment by asvae** [comment]
@gocanto This is a feature : 3. Caching routes while using api-tester is dangerous.

**Comment by gocanto** [comment]
how so?

**Comment by asvae** [comment]
@gocanto Well, my point is you cache routes only in production enviroment. Api tester is not intended for production usage as it provides no security. Hence, weird exception.

Any arguments against the feature? Except for that it's weird (which I know). : 3

**Comment by gocanto** [comment]
Whether you canchebthe rountes or not, this is a pkg that never is gonna be in prod, so there is not reason to have this set up. This is my thought

**Comment by asvae** [comment]
It could end up in prod by mistake. It's merely fool proof measure.
