### ISSUE TITLE
Error: no  found url

### ISSUE THREAD

**Issue by patelchirag123** [asvae/laravel-api-tester#31]
when i call any api after install and publish package it give me below error.

Error:

Not Found
The requested URL /api/v1.0/industries was not found on this server.
Apache/2.4.7 (Ubuntu) Server at siteproofs.net Port 80

so please help me. is there any settings or base url  i miss it.

**Comment by asvae** [comment]
I think this is somehow related to your apache config and not api tester. Either way, the details are lacking.
What do you call exactly and from where?

BTW Api tester is supposed to work right after install. You don't have to publish config, even.

**Comment by patelchirag123** [comment]
can u tell me what i miss in apache config  for solve my issue. all api list is comming but when i call api at that time it give me below error so is there any missing ?
Error:

Not Found
The requested URL /api/v1.0/industries was not found on this server.
Apache/2.4.7 (Ubuntu) Server at siteproofs.net Port 80

**Comment by asvae** [comment]
// api list
Do you mean route list?

// the details are lacking
Well. I mean like seriously lacking. Screen/gif with exact actions, console output, project structure, apache config, api tester version etc are probably crucial.

I'm not any much an expert with apache config though. With other stuff I can help.
