### ISSUE TITLE
Enable wiki!

### ISSUE THREAD

**Issue by nyedidikeke** [asvae/laravel-api-tester#9]
@asvae: It will be great to have wiki enabled for contributions on the documentation on the project.

**Comment by greabock** [comment]
Hi @nyedidikeke! Now the package isn't stable enough for documentation. We have some very interesting ideas that have to be implemented. But anyway, i think @asvae will open wiki for contribution soon. Thank you for reminding!

**Comment by nyedidikeke** [comment]
Well noted @greabock.

**Comment by asvae** [comment]
@nyedidikeke [wiki enabled](https://github.com/asvae/laravel-api-tester/issues). 

Thanks for mentioning.
